Traceback (most recent call last):
  File "/Users/josh/Documents/GitHub/hickmanjv/CS_4085 Python/Book Examples/debugging.py", line 31, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
